# Generated by Django 4.1 on 2022-11-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_content_content_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='posts.post'),
        ),
    ]
