# Generated by Django 4.1 on 2022-12-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
