# Generated by Django 4.1 on 2022-12-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
