# Generated by Django 4.1 on 2022-12-12 07:19

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_last_name_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='user_profile', validators=[users.validators.validate_file_size]),
        ),
    ]
